version: '3'
services:
  laravel-app:
    build:
      context: ./laravel-app
    container_name: laravel-app
    working_dir: /var/www
    ports:
      - "8000:80"  # Laravelアプリケーションのポート
    networks:
      - unitask-net
    volumes:
      - ./laravel-app:/var/www
    depends_on:
      - database  # データベースサービスが起動するのを待つ
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=unitask
      - DB_USERNAME=root
      - DB_PASSWORD=root

  nextjs-app:
    build:
      context: ./nextjs-app
    container_name: nextjs-app
    ports:
      - "3000:3000"  # Next.jsアプリケーションのポート
    networks:
      - unitask-net
    volumes:
      - ./nextjs-app:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://laravel-app:80/api  # Laravel APIのURL

  nginx:
    image: nginx 
    ports:
      - 80:80 
    volumes:
      - ./laravel-app:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nextjs-app
      - laravel-app
  

  database:
    image: mysql:5.7
    container_name: unitask-db
    ports:
      - "3306:3306"  # データベースのポート
    networks:
      - unitask-net
    environment:
      - MYSQL_DATABASE=unitask
      - MYSQL_ROOT_PASSWORD=root

networks:
  unitask-net:
